server:
  port: 8081
  servlet:
    context-path: / #项目的上下文路径
#连接池
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tourism_plate?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      idle-timeout: 60000
      maximum-pool-size: 30
      minimum-idle: 10
  thymeleaf:
    cache: false #关闭缓存
# mybatis-plus:
mybatis-plus:
  mapper-locations: classpath:/mybatis/*.xml #加载映射文件
  type-aliases-package: com.nxg.domain #别名搜索的包
  configuration:
    lazy-loading-enabled: true #打开懒加载
    aggressive-lazy-loading: false #关闭积极懒加载
#日志
logging:
  level:
    com.nxg: debug